### ISSUE TITLE
MongoDB replica set with authentication fails to start

### ISSUE THREAD

**Issue by romanlytvyn** [cvallance/mongo-k8s-sidecar#43]
How do we setup authentication or define a root user?

So far I have tried:

1. Setting `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` environment variables on mongo container. Mongo container fails to start with "Error: couldn't add user: not master :" which is fair since we pass `--replSet` flag and it tries adding a user before rs.initiate();
2. Passing `--auth` flag to mongod and running post start script on container to add a root user:
```
sleep 5;
mongo --eval 'rs.initiate()';
mongo --eval 'db=db.getSiblingDB("admin");db.createUser({ user: "root", pwd: "root", roles: [{ role: "root", db: "admin" }]})';
```
The user is added successfully but sidecar fails with: 
`The hosts mongo-0:27017 and 10.0.12.57:27017 all map to this node in new configuration version 2 for replica set rs0`
as it tries to add the same replica again as `mongo-0` is `10.0.12.57`.

So what's the proper way of enabling authentication?

**Comment by romanlytvyn** [comment]
I have notice there is #38 and #39.
@cvallance Could you please explain how to set up a root user during startup?

**Comment by romanlytvyn** [comment]
I've come up with some kind of a workaround:
```
...
containers:
  - name: mongo
    image: mongo
    command:
    - /bin/sh
    - -c
    - >
      if [ -f /data/db/key ]; then
        mongod --keyFile /data/db/key --replSet rs0;
      else
        mongod --auth;
      fi;
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - >
            if [ ! -f /data/db/key ]; then
              sleep 5;

              echo "SOMESTRONGPASSWORD" > /data/db/key
              chmod 600 /data/db/key

              if [ "$HOSTNAME" = "mongo-0" ]; then
                mongo --eval 'db = db.getSiblingDB("admin"); db.createUser({ user: "root", pwd: "root", roles: [{ role: "root", db: "admin" }]});';
              fi;

              mongod --shutdown;
            fi;
    ports:
      - containerPort: 27017
    volumeMounts:
      - name: mongo-persistent-storage
        mountPath: /data/db
  - name: mongo-sidecar
    image: cvallance/mongo-k8s-sidecar
    env:
      - name: MONGO_SIDECAR_POD_LABELS
        value: "role=mongo,environment=test"
      - name: MONGODB_DATABASE
        value: "admin"
      - name: MONGODB_USERNAME
        value: "root"
      - name: MONGODB_PASSWORD
        value: "root"
...
```

The idea is to start a container without `--replSet` (to be able to add a user without `rs.initiate()`), create a key file on container start and add a user on primary node (`mongo-0`) and restart container with `--keyFile` and `--replSet`.

Please let me know if there is a proper way of doing this.

**Comment by jordanjennings** [comment]
@romanlytvyn looks like #38 and #39 just added a way for the sidecar to use existing authentication, not a way for it to configure it for you. Are you still using the workaround you posted above? Any updated approaches you have figured out?

**Comment by romanlytvyn** [comment]
Hey @jordanjennings , I did not have much time to spend on the investigation so for now that's what I'm using, workaround does the job.

**Comment by zelentsovl** [comment]
Hi @romanlytvyn ,

I'm trying to use your workaround and get 

{"log":"2017-11-08T13:53:35.497+0000 I ACCESS   [main] permissions on /data/db/k                                                                              ey are too open\n","stream":"stdout","time":"2017-11-08T13:53:35.498584132Z"}

looks like chmod 600 doesn't work for some reason.

**Comment by cvallance** [comment]
Yeah, the sidecar doesn't setup authentication, that's up to the user.

**Comment by supereagle** [comment]
@cvallance Any way of enabling authentication now？

**Comment by nrobert13** [comment]
@supereagle you can enable auth with the offiicial mongo docker images setting the appropriate ENV variables, like this:
```
      containers:
        - name: mongo
          image: mongo:4.0
          imagePullPolicy: Always
          args:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--keyFile"
            - /data/db/keyfile
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo
                key: user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo
                key: pwd
...
```

and injecting a keyfile from a secret for ex:

```
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
          - name: keyfile
            mountPath: "/data/db"
...
      volumes:
      - name: keyfile
        secret:
          secretName: mongo
          items:
          - key: key
            path: keyfile
```
