### ISSUE TITLE
Broken with kubernetes 1.6 with RBAC

### ISSUE THREAD

**Issue by mellotron** [cvallance/mongo-k8s-sidecar#44]
The sidecar fails on 1.6 with RBAC with:

```
Error in workloop { [Error: User "system:serviceaccount:wekan-test:default" cannot list pods at the cluster scope.]
  message: 'User "system:serviceaccount:wekan-test:default" cannot list pods at the cluster scope.',
  statusCode: 403 }
```

**Comment by mellotron** [comment]
Working with:

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: wekan-test
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:serviceaccount:wekan-test:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: wekan-test
```
