### ISSUE TITLE
MongoDB Stateful Set, Each Read/Write  into random Instance, then does not find entries

### ISSUE THREAD

**Issue by nottinhill** [cvallance/mongo-k8s-sidecar#58]
Worst case scenario is happening as in subject described. I have a StatefulSet running and on database write and read it uses random instances (mongo-0, mongo-1) and does not find values it needs.

My deployment of the app has this:

```
  spec:
      hostAliases:
        - ip: "10.2.6.112"
          hostnames:
            - "mongo-0"
            - "mongo-0.mongo"
            - "mongo-0.mongo.yourTLD.net"
     ...
```

Then I do:

If i run `rs.initiate()` on all mongo set members, one is designated as "secondary" and two as "other". All three tell me:

```
> rs.initiate()
{
	"info2" : "no configuration specified. Using a default configuration for the set",
	"me" : "mongo-2:27017",
	"ok" : 1
}

```

Then I do as in Readme of this project:

and/or according to sidecar github project documentation:

```
        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: mongo # your statefulSet name 
in MONGODB_URI:

         value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/YOUR_DB?replicaSet=mongo&auth=admin"
```

How can I ensure only 1 DB is used or the others are replicas. At the moment the replication obviously does not work.
