### ISSUE TITLE
 StatefulSets' stable network ID error

### ISSUE THREAD

**Issue by zhoulouzi** [cvallance/mongo-k8s-sidecar#61]
# logs from sidecar container:
Error in workloop { MongoError: failed to connect to server [192.168.199.136:27017] on first connect [MongoError: connect ECONNREFUSED 192.168.199.136:27017]
    at Pool.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
  name: 'MongoError',
  message: 'failed to connect to server [192.168.199.136:27017] on first connect [MongoError: connect ECONNREFUSED 192.168.199.136:27017]' }_

# my yaml:

```
apiVersion: v1
kind: Service
metadata:
    name: mongodb-shard1
    labels:
        name: mongo
spec:
    ports:
      - port: 27017
        targetPort: 27017
    clusterIP: None
    selector:
      role: mongo-shard1
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
    name: mongod
spec:
    serviceName: mongodb-shard1
    replicas: 3
    template:
        metadata:
            labels:
              role: mongo-shard1
              environment: test
        spec:
            terminationGracePeriodSeconds: 10
            volumes:
              - name: mongodb-volume
                emptyDir: {}
            containers:
              - name: mongod-container
                image: mongo:latest
                command:
                  - "mongod"
                  - "--replSet"
                  - "shard1set"
                  - "--shardsvr"
                  - "--port"
                  - "27017"
                  - "--smallfiles"
                  - "--noprealloc"
                ports:
                  - containerPort: 27017
                volumeMounts:
                  - name: mongodb-volume
                    mountPath: /data/db
              - name: mongo-sidecar
                image: cvallance/mongo-k8s-sidecar:latest
                env:
                  - name: MONGO_SIDECAR_POD_LABELS
                    value: "role=mongo-shard1,environment=test"
                env:
                  - name: KUBERNETES_MONGO_SERVICE_NAME
                    value: mongodb-shard1
                env:
                  - name: KUBERNETES_CLUSTER_DOMAIN
                    value: cluster.local

```

-------
it seems that rs.initail() didnot work!
