### ISSUE TITLE
Mongo-SideCar unable to connect to Mongodb

### ISSUE THREAD

**Issue by joshorig** [cvallance/mongo-k8s-sidecar#68]
```
MacBook-Pro-2:StatefulSet joshuacassidy$ kubectl logs mongo-0 -c mongo-sidecar

> mongo-k8s-sidecar@0.1.0 start /opt/cvallance/mongo-k8s-sidecar
> forever src/index.js

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Using mongo port: 27017
Starting up mongo-k8s-sidecar
The cluster domain 'cluster.local' was successfully verified.
Error in workloop { MongoError: failed to connect to server [10.244.1.8:27017] on first connect [MongoError: connect ECONNREFUSED 10.244.1.8:27017]
    at Pool.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:125:13)
    at Pool.emit (events.js:221:7)
    at Connection.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:326:30)
    at emitTwo (events.js:135:13)
    at Connection.emit (events.js:224:7)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
  name: 'MongoError',
  message: 'failed to connect to server [10.244.1.8:27017] on first connect [MongoError: connect ECONNREFUSED 10.244.1.8:27017]' }
```
Hi deplying the example statefulset to azure seems to give me the following error. Any ideas? Is there any specific configuration required for azure?

I am using the azure storage config as mentioned:
...
azure_ssd.yaml
...

I also attempted to add the following environment vairables:

...
  - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
            - name: KUBE_NAMESPACE
              value: "dev"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongo"
...

**Comment by joshorig** [comment]
So as of MongoDB 3.6, the default for MongoDB is to bind to localhost 127.0.0.1 which means it cannot accept the connection from the mongo-sidecar container by default.

To resolve set the bindip as a command option in the service file:

`mongo-statefulset.yaml`

Example:

```
containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
```
