### ISSUE TITLE
Support Horizontal Pod Auto-scaling

### ISSUE THREAD

**Issue by serain** [cvallance/mongo-k8s-sidecar#96]
It doesn't appear to be possible to set this up with an HPA:

```
apiVersion: v1
kind: Namespace
metadata:
  name: mongo
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: hostvm-configurer
  namespace: mongo
  labels:
    app: startup-script
spec:
  template:
    metadata:
      labels:
        app: startup-script
    spec:
      hostPID: true
      containers:
      - name: hostvm-configurer-container
        image: gcr.io/google-containers/startup-script:v1
        securityContext:
          privileged: true
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            set -o errexit
            set -o pipefail
            set -o nounset
            
            # Disable hugepages
            echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
            echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: mongo
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mongo
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: mongo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Headless service (clusterIP: None)
# this prevents the service from acting as a load balancer
# allowing each pod to be reached directly
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongo
spec:
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        env: staging
        replicaset: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: mongo
      containers:
      - name: mongo
        image: mongo:4.0.6-xenial
        command:
          - mongod
          - "--wiredTigerCacheSizeGB"
          - "0.25"
          - "--bind_ip"
          - "0.0.0.0"
          - "--replSet"
          - MainRepSet
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
        resources:
          requests:
            cpu: 0.5
            memory: 0.5Gi
          limits:
            cpu: 1
            memory: 1Gi
      - name: mongosidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,env=staging"
          - name: KUBE_NAMESPACE
            value: "mongo"
          - name: KUBERNETES_MONGO_SERVICE_NAME
            value: "mongo"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mongo
  namespace: mongo
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: StatefulSet
    name: mongo
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

With the above I get errors related to the hpa being unable to fetch CPU usage:

```
~/P/kube-mongo $ kubectl describe hpa -n mongo
Name:                                                  mongo
Namespace:                                             mongoLabels:                                                <none>
Annotations:                                           <none>CreationTimestamp:                                     Sat, 23 Feb 2019 18:33:12 +0000
Reference:                                             StatefulSet/mongo
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          1Max replicas:                                          3
StatefulSet pods:                                      1 current / 0 desiredConditions:
  Type           Status  Reason                   Message  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale 
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpuEvents:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedGetResourceMetric       98s (x3 over 2m8s)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  98s (x3 over 2m8s)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedGetResourceMetric       8s (x6 over 83s)    horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  8s (x6 over 83s)    horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu
```

If I remove the sidecar, the `mongo` pod and the HPA function as expected.

I'm happy to try and fix this myself if you have any hints?
